# Generated by Django 4.2.5 on 2025-01-14 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_isprof_customuser_is_professor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='prof',
            new_name='Professor_id',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='isStu',
            new_name='is_Student',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_Student': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
